### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by makew0rld** [ianremmler/tabbycat#1]
I tried passing a line that began with `<!--` and ended with `-->` to the regular Go tabwriter, with the ignore HTML flag enabled. But the line didn't seem to be ignored. Is there a step I'm missing?

**Comment by ianremmler** [comment]
Wow, I completely forgot I made this! It's a terrible hack, and you probably shouldn't use it.

But with that said... With FilterHTML, tabwriter ignores the length of HTML tags when calculating the alignment, but still writes the text. tabbycat wraps whatever matches the ignore regexp with an HTML comment and hands it to tabwriter, which aligns the text ignoring the length of the comment, then tabbycat strips the comment tags back off.

I made this because I was trying to align some text that included embedded ANSI color escape sequences, which I wanted to include in the output but whose length I did not want to count when aligning the text. Again, it's a terrible hack.

I hope that makes sense.
